rules:
  - pattern: '/'
    data:
      # apps: 'https://api.github.com/repos/feramhq/cli-apps/contents/apps'
      apps:
        type: file
        fetch: all
        path: './apps/*/main.yaml'
    template: 'index.html'

  - pattern: '/static/{{path:**}}'
    static: true
    data:
      file: 'file://./static/{{path}}'

  - pattern: '/images/{{path:**}}'
    static: true
    data:
      file: 'file://./images/{{path}}'

  - pattern: '/apps/{{name:*}}/main.png'
    static: true
    data:
      - file: 'file://./apps/{{name}}/main.png'

  - pattern: '/apps/{{name:*}}'
    data:
      app: 'file://apps/{{name}}/main.yaml'
      # app:
      #   type: 'https'
      #   uri: 'https://raw.githubusercontent.com/feramhq/cli-apps/master/apps/{{name}}'
      #   uri: 'https://api.github.com/repos/feramhq/cli-apps/contents/apps/{{name}}'
      #   force-mime-type: 'text/x-yaml'
    template: 'app.html'
