rules:
  - pattern: '/'
    data:
      # apps: 'https://api.github.com/repos/feramhq/cli-apps/contents/apps'
      apps:
        type: file
        fetch: all
        path: './apps/*/main.yaml'
        order: -mtime
    template: 'index.html'

  - pattern: '/static/{{path:**}}'
    static: true
    data:
      file: 'file://./static/{{path}}'

  - pattern: '/images/{{path:**}}'
    static: true
    data:
      file: 'file://./images/{{path}}'

  - pattern: '/apps/{{name:*}}'
    data:
      app: 'file://apps/{{name}}/main.yaml'
    template: 'app.html'

  - pattern: '/apps/{{name:*}}/installation'
    data:
      app: 'file://apps/{{name}}/main.yaml'
    template: 'installation.html'

  - pattern: '/apps/{{appName:*}}/{{fileName:**}}'
    static: true
    data:
      - file: 'file://./apps/{{appName}}/{{fileName}}'
